- name: configuring mongodb server
  become: yes
  hosts: mongodb
  tasks:
  - name: copy mongodb repo #http://docs.ansible.com/ansible/latest/collections/ansible/builtin/copy_module.html
    ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongodb.repo

  - name: Install mongodb server
    ansible.builtin.dnf:
      name: mongodb-org
      state: present